import { vehicleListSchema } from '../vehicle.schemas';
import { MOCK_VEHICLE_DISCLAIMER } from '../vehicle.constants';
import type { Vehicle, VehicleFeature, VehicleImage } from '../vehicle.types';

const MOCK_IMAGES = {
  exterior1: '/images/vehicles/mock/exterior-01.jpg',
  exterior2: '/images/vehicles/mock/exterior-02.jpg',
  exterior3: '/images/vehicles/mock/exterior-03.jpg',
  exterior4: '/images/vehicles/mock/exterior-04.jpg',
  interior1: '/images/vehicles/mock/interior-01.jpg',
  interior2: '/images/vehicles/mock/interior-02.jpg',
} as const;

function buildImages(
  vehicleLabel: string,
  primary: (typeof MOCK_IMAGES)[keyof typeof MOCK_IMAGES],
  secondary: (typeof MOCK_IMAGES)[keyof typeof MOCK_IMAGES][] = [],
): VehicleImage[] {
  const gallery = [primary, ...secondary];
  return gallery.map((url, index) => ({
    id: `${vehicleLabel}-img-${index + 1}`,
    url,
    alt: `${vehicleLabel} — development placeholder image ${index + 1}`,
    sortOrder: index,
    isPrimary: index === 0,
  }));
}

function buildFeatures(entries: Array<[string, string | null]>): VehicleFeature[] {
  return entries.map(([label, category], index) => ({
    id: `feature-${index + 1}`,
    label,
    category,
  }));
}

/** Raw mock inventory — validated once via `getValidatedMockVehicles()`. */
const MOCK_VEHICLES_RAW: Vehicle[] = [
  {
    id: 'veh-mock-001',
    externalStockId: 'AT-MOCK-1001',
    slug: '2022-bmw-330i-m-sport',
    make: 'BMW',
    model: '3 Series',
    derivative: '330i M Sport',
    registrationYear: 2022,
    registrationNumber: 'BM22 KXR',
    mileage: 18450,
    price: 32995,
    previousPrice: 34995,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Black Sapphire',
    engineSize: '2.0L',
    doors: 4,
    seats: 5,
    shortDescription: 'Well-appointed M Sport saloon with strong service history.',
    fullDescription: `Development mock listing for a premium petrol saloon. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'M Sport specification with low mileage',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2022 BMW 330i M Sport', MOCK_IMAGES.exterior1, [
      MOCK_IMAGES.exterior2,
      MOCK_IMAGES.interior1,
    ]),
    featuredImage: MOCK_IMAGES.exterior1,
    features: buildFeatures([
      ['M Sport exterior styling', 'Exterior'],
      ['Heated front seats', 'Interior'],
      ['Parking sensors front and rear', 'Safety'],
      ['Apple CarPlay', 'Technology'],
    ]),
    isFeatured: true,
    isPublished: true,
    firstRegisteredAt: '2022-03-18T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-01-12T09:00:00.000Z',
    updatedAt: '2026-03-01T11:30:00.000Z',
  },
  {
    id: 'veh-mock-002',
    externalStockId: 'AT-MOCK-1002',
    slug: '2021-mercedes-benz-c300-amg-line',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    derivative: 'C300 AMG Line',
    registrationYear: 2021,
    registrationNumber: 'ME21 HFD',
    mileage: 24680,
    price: 29995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Polar White',
    engineSize: '2.0L',
    doors: 4,
    seats: 5,
    shortDescription: 'AMG Line trim with digital cockpit and comfort pack.',
    fullDescription: `Mock Mercedes-Benz C-Class inventory record. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'AMG Line with panoramic roof',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2021 Mercedes-Benz C300 AMG Line', MOCK_IMAGES.exterior2, [
      MOCK_IMAGES.interior2,
    ]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['AMG Line interior and exterior', 'Exterior'],
      ['Panoramic sunroof', 'Comfort'],
      ['Active parking assist', 'Safety'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2021-07-09T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-01-18T10:15:00.000Z',
    updatedAt: '2026-02-20T08:45:00.000Z',
  },
  {
    id: 'veh-mock-003',
    externalStockId: 'AT-MOCK-1003',
    slug: '2020-audi-a4-s-line',
    make: 'Audi',
    model: 'A4',
    derivative: '35 TFSI S line',
    registrationYear: 2020,
    registrationNumber: 'AU20 PLM',
    mileage: 31200,
    price: 24995,
    previousPrice: 26495,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Daytona Grey',
    engineSize: '2.0L',
    doors: 4,
    seats: 5,
    shortDescription: 'S line specification with virtual cockpit and LED lighting.',
    fullDescription: `Mock Audi A4 listing for development UI work. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Reserved — enquiry welcome',
    status: 'RESERVED',
    lifecycleState: 'SALE_IN_PROGRESS',
    images: buildImages('2020 Audi A4 S line', MOCK_IMAGES.exterior3, [MOCK_IMAGES.interior1]),
    featuredImage: MOCK_IMAGES.exterior3,
    features: buildFeatures([
      ['S line styling pack', 'Exterior'],
      ['Virtual cockpit', 'Technology'],
      ['LED headlights', 'Exterior'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2020-05-22T00:00:00.000Z',
    soldAt: null,
    createdAt: '2025-12-02T14:00:00.000Z',
    updatedAt: '2026-03-10T16:20:00.000Z',
  },
  {
    id: 'veh-mock-004',
    externalStockId: 'AT-MOCK-1004',
    slug: '2019-porsche-911-carrera',
    make: 'Porsche',
    model: '911',
    derivative: 'Carrera',
    registrationYear: 2019,
    registrationNumber: 'PO19 RSR',
    mileage: 22100,
    price: 78995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'COUPE',
    colour: 'Jet Black',
    engineSize: '3.0L',
    doors: 2,
    seats: 4,
    shortDescription: 'Iconic Carrera with sports exhaust and PCCB brakes.',
    fullDescription: `Fictional Porsche 911 mock record for premium hero/detail testing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Featured performance coupe',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2019 Porsche 911 Carrera', MOCK_IMAGES.exterior4, [
      MOCK_IMAGES.exterior1,
      MOCK_IMAGES.interior2,
    ]),
    featuredImage: MOCK_IMAGES.exterior4,
    features: buildFeatures([
      ['Sport Chrono Package', 'Performance'],
      ['BOSE surround sound', 'Technology'],
      ['Sport exhaust system', 'Performance'],
    ]),
    isFeatured: true,
    isPublished: true,
    firstRegisteredAt: '2019-09-14T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-01T09:30:00.000Z',
    updatedAt: '2026-03-05T12:00:00.000Z',
  },
  {
    id: 'veh-mock-005',
    externalStockId: 'AT-MOCK-1005',
    slug: '2023-range-rover-sport-hse',
    make: 'Land Rover',
    model: 'Range Rover Sport',
    derivative: 'P400e HSE',
    registrationYear: 2023,
    registrationNumber: 'LR73 VNT',
    mileage: 9800,
    price: 84995,
    previousPrice: null,
    fuelType: 'PLUG_IN_HYBRID',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Santorini Black',
    engineSize: '3.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'Plug-in hybrid HSE arriving shortly — register interest.',
    fullDescription: `Mock coming-soon Range Rover Sport record. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Due in next week',
    status: 'COMING_SOON',
    lifecycleState: 'DUE_IN',
    images: buildImages('2023 Range Rover Sport HSE', MOCK_IMAGES.exterior2, [
      MOCK_IMAGES.exterior3,
    ]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['HSE specification', 'Comfort'],
      ['Meridian sound system', 'Technology'],
      ['Configurable interior ambient lighting', 'Interior'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2023-11-02T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-03-08T08:00:00.000Z',
    updatedAt: '2026-03-12T09:15:00.000Z',
  },
  {
    id: 'veh-mock-006',
    externalStockId: 'AT-MOCK-1006',
    slug: '2022-volvo-xc60-recharge',
    make: 'Volvo',
    model: 'XC60',
    derivative: 'Recharge T8 Inscription',
    registrationYear: 2022,
    registrationNumber: 'VO22 EVC',
    mileage: 16750,
    price: 41995,
    previousPrice: 43995,
    fuelType: 'PLUG_IN_HYBRID',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Crystal White',
    engineSize: '2.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'Efficient plug-in hybrid SUV with high specification.',
    fullDescription: `Mock Volvo XC60 Recharge listing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'One owner from new',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2022 Volvo XC60 Recharge', MOCK_IMAGES.exterior3, [MOCK_IMAGES.interior2]),
    featuredImage: MOCK_IMAGES.exterior3,
    features: buildFeatures([
      ['Pilot Assist', 'Safety'],
      ['Heated steering wheel', 'Comfort'],
      ['Power tailgate', 'Convenience'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2022-06-30T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-01-25T13:45:00.000Z',
    updatedAt: '2026-02-28T10:10:00.000Z',
  },
  {
    id: 'veh-mock-007',
    externalStockId: 'AT-MOCK-1007',
    slug: '2021-lexus-is-300h-f-sport',
    make: 'Lexus',
    model: 'IS',
    derivative: '300h F Sport',
    registrationYear: 2021,
    registrationNumber: 'LE21 HBR',
    mileage: 20340,
    price: 27995,
    previousPrice: null,
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Graphite Black',
    engineSize: '2.5L',
    doors: 4,
    seats: 5,
    shortDescription: 'Self-charging hybrid saloon with F Sport styling.',
    fullDescription: `Mock Lexus IS hybrid listing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Hybrid efficiency with F Sport presence',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2021 Lexus IS 300h F Sport', MOCK_IMAGES.exterior1, [
      MOCK_IMAGES.interior1,
    ]),
    featuredImage: MOCK_IMAGES.exterior1,
    features: buildFeatures([
      ['F Sport exterior pack', 'Exterior'],
      ['Mark Levinson audio', 'Technology'],
      ['Lane keep assist', 'Safety'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2021-02-11T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-10T11:00:00.000Z',
    updatedAt: '2026-03-02T15:40:00.000Z',
  },
  {
    id: 'veh-mock-008',
    externalStockId: 'AT-MOCK-1008',
    slug: '2020-jaguar-f-pace-r-dynamic',
    make: 'Jaguar',
    model: 'F-PACE',
    derivative: 'P250 R-Dynamic S',
    registrationYear: 2020,
    registrationNumber: 'JA20 RDY',
    mileage: 28900,
    price: 31995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Firenze Red',
    engineSize: '2.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'R-Dynamic SUV with configurable dynamics and premium audio.',
    fullDescription: `Mock Jaguar F-PACE listing under reservation. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Currently reserved',
    status: 'RESERVED',
    lifecycleState: 'SALE_IN_PROGRESS',
    images: buildImages('2020 Jaguar F-PACE R-Dynamic', MOCK_IMAGES.exterior4, [
      MOCK_IMAGES.interior2,
    ]),
    featuredImage: MOCK_IMAGES.exterior4,
    features: buildFeatures([
      ['R-Dynamic body styling', 'Exterior'],
      ['Meridian sound', 'Technology'],
      ['All-wheel drive', 'Performance'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2020-08-19T00:00:00.000Z',
    soldAt: null,
    createdAt: '2025-11-20T09:20:00.000Z',
    updatedAt: '2026-03-09T13:05:00.000Z',
  },
  {
    id: 'veh-mock-009',
    externalStockId: 'AT-MOCK-1009',
    slug: '2024-land-rover-defender-110',
    make: 'Land Rover',
    model: 'Defender',
    derivative: '110 X-Dynamic HSE',
    registrationYear: 2024,
    registrationNumber: 'LD24 XDY',
    mileage: 4200,
    price: 72995,
    previousPrice: null,
    fuelType: 'DIESEL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Pangea Green',
    engineSize: '3.0L',
    doors: 5,
    seats: 7,
    shortDescription: 'Seven-seat Defender due in — expressions of interest welcome.',
    fullDescription: `Mock Defender coming-soon record. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Incoming stock',
    status: 'COMING_SOON',
    lifecycleState: 'DUE_IN',
    images: buildImages('2024 Land Rover Defender 110', MOCK_IMAGES.exterior2, [
      MOCK_IMAGES.exterior4,
    ]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['X-Dynamic pack', 'Exterior'],
      ['Three-row seating', 'Interior'],
      ['Terrain Response 2', 'Performance'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2024-04-03T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-03-01T07:30:00.000Z',
    updatedAt: '2026-03-11T18:00:00.000Z',
  },
  {
    id: 'veh-mock-010',
    externalStockId: 'AT-MOCK-1010',
    slug: '2019-bmw-x5-xdrive40i',
    make: 'BMW',
    model: 'X5',
    derivative: 'xDrive40i M Sport',
    registrationYear: 2019,
    registrationNumber: 'BM19 X5M',
    mileage: 45200,
    price: 36995,
    previousPrice: 38995,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Phytonic Blue',
    engineSize: '3.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'Recently sold M Sport X5 — example sold inventory record.',
    fullDescription: `Mock sold BMW X5 for recently-sold views. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Sold',
    status: 'SOLD',
    lifecycleState: 'SOLD',
    images: buildImages('2019 BMW X5 xDrive40i', MOCK_IMAGES.exterior3, [MOCK_IMAGES.interior1]),
    featuredImage: MOCK_IMAGES.exterior3,
    features: buildFeatures([
      ['M Sport package', 'Exterior'],
      ['Head-up display', 'Technology'],
      ['Tow bar preparation', 'Convenience'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2019-01-26T00:00:00.000Z',
    soldAt: '2026-02-14T16:00:00.000Z',
    createdAt: '2025-10-05T10:00:00.000Z',
    updatedAt: '2026-02-14T16:30:00.000Z',
  },
  {
    id: 'veh-mock-011',
    externalStockId: 'AT-MOCK-1011',
    slug: '2018-mercedes-benz-e220d-amg-line',
    make: 'Mercedes-Benz',
    model: 'E-Class',
    derivative: 'E220d AMG Line',
    registrationYear: 2018,
    registrationNumber: 'ME18 ECL',
    mileage: 53800,
    price: 21995,
    previousPrice: null,
    fuelType: 'DIESEL',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Obsidian Black',
    engineSize: '2.0L',
    doors: 4,
    seats: 5,
    shortDescription: 'Efficient diesel executive saloon — sold mock example.',
    fullDescription: `Mock sold Mercedes-Benz E-Class record. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Sold',
    status: 'SOLD',
    lifecycleState: 'SOLD',
    images: buildImages('2018 Mercedes-Benz E220d', MOCK_IMAGES.exterior1, [MOCK_IMAGES.interior2]),
    featuredImage: MOCK_IMAGES.exterior1,
    features: buildFeatures([
      ['AMG Line trim', 'Exterior'],
      ['Comand Online navigation', 'Technology'],
      ['Keyless entry', 'Convenience'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2018-10-12T00:00:00.000Z',
    soldAt: '2026-01-28T11:45:00.000Z',
    createdAt: '2025-09-18T08:30:00.000Z',
    updatedAt: '2026-01-28T12:00:00.000Z',
  },
  {
    id: 'veh-mock-012',
    externalStockId: 'AT-MOCK-1012',
    slug: '2020-audi-q5-s-line',
    make: 'Audi',
    model: 'Q5',
    derivative: '40 TDI S line',
    registrationYear: 2020,
    registrationNumber: 'AU20 Q5S',
    mileage: 36750,
    price: 28995,
    previousPrice: 30495,
    fuelType: 'DIESEL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Navarra Blue',
    engineSize: '2.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'Popular S line Q5 — sold mock inventory item.',
    fullDescription: `Mock sold Audi Q5 listing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Sold',
    status: 'SOLD',
    lifecycleState: 'SOLD',
    images: buildImages('2020 Audi Q5 S line', MOCK_IMAGES.exterior2, [MOCK_IMAGES.exterior3]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['S line exterior', 'Exterior'],
      ['Quattro all-wheel drive', 'Performance'],
      ['Electric tailgate', 'Convenience'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2020-03-07T00:00:00.000Z',
    soldAt: '2026-03-03T14:20:00.000Z',
    createdAt: '2025-11-01T12:10:00.000Z',
    updatedAt: '2026-03-03T14:25:00.000Z',
  },
  {
    id: 'veh-mock-013',
    externalStockId: 'AT-MOCK-1013',
    slug: '2019-mini-cooper-s',
    make: 'MINI',
    model: 'Hatch',
    derivative: 'Cooper S',
    registrationYear: 2019,
    registrationNumber: 'MN19 COS',
    mileage: 27400,
    price: 17995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'MANUAL',
    bodyType: 'HATCHBACK',
    colour: 'Chili Red',
    engineSize: '2.0L',
    doors: 3,
    seats: 4,
    shortDescription: 'Compact Cooper S — sold mock hatchback example.',
    fullDescription: `Mock sold MINI Cooper S record. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Sold',
    status: 'SOLD',
    lifecycleState: 'SOLD',
    images: buildImages('2019 MINI Cooper S', MOCK_IMAGES.exterior4, [MOCK_IMAGES.interior1]),
    featuredImage: MOCK_IMAGES.exterior4,
    features: buildFeatures([
      ['John Cooper Works aerodynamic kit', 'Exterior'],
      ['Sport seats', 'Interior'],
      ['Bluetooth connectivity', 'Technology'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2019-06-21T00:00:00.000Z',
    soldAt: '2026-02-02T10:00:00.000Z',
    createdAt: '2025-10-22T15:00:00.000Z',
    updatedAt: '2026-02-02T10:05:00.000Z',
  },
  {
    id: 'veh-mock-014',
    externalStockId: 'AT-MOCK-1014',
    slug: '2023-tesla-model-3-long-range',
    make: 'Tesla',
    model: 'Model 3',
    derivative: 'Long Range',
    registrationYear: 2023,
    registrationNumber: 'TE23 LR1',
    mileage: 11200,
    price: 36995,
    previousPrice: null,
    fuelType: 'ELECTRIC',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Pearl White',
    engineSize: null,
    doors: 4,
    seats: 5,
    shortDescription: 'Long Range electric saloon with enhanced autopilot.',
    fullDescription: `Mock Tesla Model 3 featured electric listing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Featured EV with strong range',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2023 Tesla Model 3 Long Range', MOCK_IMAGES.exterior3, [
      MOCK_IMAGES.interior2,
      MOCK_IMAGES.exterior1,
    ]),
    featuredImage: MOCK_IMAGES.exterior3,
    features: buildFeatures([
      ['Enhanced Autopilot', 'Technology'],
      ['Heat pump', 'Efficiency'],
      ['Premium connectivity', 'Technology'],
    ]),
    isFeatured: true,
    isPublished: true,
    firstRegisteredAt: '2023-02-16T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-15T09:45:00.000Z',
    updatedAt: '2026-03-06T11:10:00.000Z',
  },
  {
    id: 'veh-mock-016',
    externalStockId: 'AT-MOCK-1016',
    slug: '2022-audi-q7-s-line',
    make: 'Audi',
    model: 'Q7',
    derivative: '55 TFSI S line',
    registrationYear: 2022,
    registrationNumber: 'AU22 Q7S',
    mileage: 19800,
    price: 54995,
    previousPrice: 56995,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Glacier White',
    engineSize: '3.0L',
    doors: 5,
    seats: 7,
    shortDescription: 'Seven-seat S line Q7 with adaptive air suspension.',
    fullDescription: `Mock Audi Q7 listing for pagination and filter testing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Seven seats with S line specification',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2022 Audi Q7 S line', MOCK_IMAGES.exterior1, [
      MOCK_IMAGES.exterior3,
      MOCK_IMAGES.interior1,
    ]),
    featuredImage: MOCK_IMAGES.exterior1,
    features: buildFeatures([
      ['S line exterior pack', 'Exterior'],
      ['Adaptive air suspension', 'Performance'],
      ['Virtual cockpit plus', 'Technology'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2022-09-08T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-20T10:00:00.000Z',
    updatedAt: '2026-03-07T09:30:00.000Z',
  },
  {
    id: 'veh-mock-017',
    externalStockId: 'AT-MOCK-1017',
    slug: '2021-bmw-530i-m-sport',
    make: 'BMW',
    model: '5 Series',
    derivative: '530i M Sport',
    registrationYear: 2021,
    registrationNumber: 'BM21 M5S',
    mileage: 26400,
    price: 35995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SALOON',
    colour: 'Mineral Grey',
    engineSize: '2.0L',
    doors: 4,
    seats: 5,
    shortDescription: 'Executive M Sport saloon with comfort access and live cockpit.',
    fullDescription: `Mock BMW 5 Series listing for inventory pagination testing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'M Sport with premium interior',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2021 BMW 530i M Sport', MOCK_IMAGES.exterior2, [MOCK_IMAGES.interior2]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['M Sport brake calipers', 'Performance'],
      ['Comfort access', 'Convenience'],
      ['Live cockpit professional', 'Technology'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2021-04-19T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-18T08:20:00.000Z',
    updatedAt: '2026-03-04T14:15:00.000Z',
  },
  {
    id: 'veh-mock-018',
    externalStockId: 'AT-MOCK-1018',
    slug: '2020-mercedes-benz-glc-300-amg-line',
    make: 'Mercedes-Benz',
    model: 'GLC',
    derivative: 'GLC 300 AMG Line',
    registrationYear: 2020,
    registrationNumber: 'ME20 GLC',
    mileage: 33100,
    price: 33995,
    previousPrice: 35495,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Selenite Grey',
    engineSize: '2.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'AMG Line GLC SUV — reserved pending finance completion.',
    fullDescription: `Mock Mercedes-Benz GLC reserved listing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Reserved — similar models available',
    status: 'RESERVED',
    lifecycleState: 'SALE_IN_PROGRESS',
    images: buildImages('2020 Mercedes-Benz GLC 300', MOCK_IMAGES.exterior3, [
      MOCK_IMAGES.exterior4,
    ]),
    featuredImage: MOCK_IMAGES.exterior3,
    features: buildFeatures([
      ['AMG Line styling', 'Exterior'],
      ['360-degree camera', 'Safety'],
      ['Multibeam LED headlights', 'Exterior'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2020-11-27T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-01-30T11:40:00.000Z',
    updatedAt: '2026-03-08T16:50:00.000Z',
  },
  {
    id: 'veh-mock-019',
    externalStockId: 'AT-MOCK-1019',
    slug: '2022-porsche-macan-s',
    make: 'Porsche',
    model: 'Macan',
    derivative: 'S',
    registrationYear: 2022,
    registrationNumber: 'PO22 MCN',
    mileage: 15600,
    price: 52995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'SUV',
    colour: 'Carrara White',
    engineSize: '2.9L',
    doors: 5,
    seats: 5,
    shortDescription: 'Compact performance SUV with sport chrono and BOSE audio.',
    fullDescription: `Mock Porsche Macan S listing for premium inventory grids. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Sport Chrono and panoramic roof',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2022 Porsche Macan S', MOCK_IMAGES.exterior4, [
      MOCK_IMAGES.interior1,
      MOCK_IMAGES.exterior2,
    ]),
    featuredImage: MOCK_IMAGES.exterior4,
    features: buildFeatures([
      ['Sport Chrono Package', 'Performance'],
      ['Panoramic roof system', 'Comfort'],
      ['BOSE surround sound', 'Technology'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2022-01-14T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-22T09:10:00.000Z',
    updatedAt: '2026-03-10T10:25:00.000Z',
  },
  {
    id: 'veh-mock-020',
    externalStockId: 'AT-MOCK-1020',
    slug: '2024-ford-mustang-gt',
    make: 'Ford',
    model: 'Mustang',
    derivative: '5.0 V8 GT',
    registrationYear: 2024,
    registrationNumber: 'FO24 GT5',
    mileage: 1800,
    price: 48995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    bodyType: 'COUPE',
    colour: 'Race Red',
    engineSize: '5.0L',
    doors: 2,
    seats: 4,
    shortDescription: 'V8 GT coupe due in — register interest ahead of arrival.',
    fullDescription: `Mock coming-soon Ford Mustang GT record. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Incoming V8 GT',
    status: 'COMING_SOON',
    lifecycleState: 'DUE_IN',
    images: buildImages('2024 Ford Mustang GT', MOCK_IMAGES.exterior1, [MOCK_IMAGES.exterior4]),
    featuredImage: MOCK_IMAGES.exterior1,
    features: buildFeatures([
      ['GT performance pack', 'Performance'],
      ['B&O premium audio', 'Technology'],
      ['Adaptive suspension', 'Performance'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2024-06-12T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-03-05T07:00:00.000Z',
    updatedAt: '2026-03-12T12:40:00.000Z',
  },
  {
    id: 'veh-mock-021',
    externalStockId: 'AT-MOCK-1021',
    slug: '2023-honda-civic-type-r',
    make: 'Honda',
    model: 'Civic',
    derivative: 'Type R',
    registrationYear: 2023,
    registrationNumber: 'HO23 TPR',
    mileage: 8900,
    price: 42995,
    previousPrice: 44995,
    fuelType: 'PETROL',
    transmission: 'MANUAL',
    bodyType: 'HATCHBACK',
    colour: 'Championship White',
    engineSize: '2.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'High-performance Type R hatch with single-owner history.',
    fullDescription: `Mock Honda Civic Type R listing for pagination testing. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: 'Manual Type R with low mileage',
    status: 'AVAILABLE',
    lifecycleState: 'FORECOURT',
    images: buildImages('2023 Honda Civic Type R', MOCK_IMAGES.exterior2, [
      MOCK_IMAGES.interior2,
      MOCK_IMAGES.exterior3,
    ]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['Brembo front brakes', 'Performance'],
      ['LogR data logger', 'Technology'],
      ['Heated front seats', 'Comfort'],
    ]),
    isFeatured: false,
    isPublished: true,
    firstRegisteredAt: '2023-08-25T00:00:00.000Z',
    soldAt: null,
    createdAt: '2026-02-25T13:30:00.000Z',
    updatedAt: '2026-03-09T08:55:00.000Z',
  },
  {
    id: 'veh-mock-015',
    externalStockId: 'AT-MOCK-1015',
    slug: '2017-volkswagen-golf-r',
    make: 'Volkswagen',
    model: 'Golf',
    derivative: 'R',
    registrationYear: 2017,
    registrationNumber: 'VW17 GRF',
    mileage: 61200,
    price: 19995,
    previousPrice: null,
    fuelType: 'PETROL',
    transmission: 'MANUAL',
    bodyType: 'HATCHBACK',
    colour: 'Lapiz Blue',
    engineSize: '2.0L',
    doors: 5,
    seats: 5,
    shortDescription: 'Hidden draft record — unpublished mock vehicle.',
    fullDescription: `Unpublished mock Golf R used to test hidden inventory handling. ${MOCK_VEHICLE_DISCLAIMER}`,
    attentionGrabber: null,
    status: 'HIDDEN',
    lifecycleState: 'WASTEBIN',
    images: buildImages('2017 Volkswagen Golf R', MOCK_IMAGES.exterior2, [MOCK_IMAGES.interior1]),
    featuredImage: MOCK_IMAGES.exterior2,
    features: buildFeatures([
      ['4Motion all-wheel drive', 'Performance'],
      ['Discover Pro infotainment', 'Technology'],
    ]),
    isFeatured: false,
    isPublished: false,
    firstRegisteredAt: '2017-04-05T00:00:00.000Z',
    soldAt: null,
    createdAt: '2025-08-12T08:00:00.000Z',
    updatedAt: '2026-01-05T09:00:00.000Z',
  },
];

let validatedCache: Vehicle[] | null = null;

/** Returns mock vehicles validated against the Zod Vehicle schema (cached). */
function getValidatedMockVehicles(): Vehicle[] {
  if (validatedCache) return validatedCache;
  validatedCache = vehicleListSchema.parse(MOCK_VEHICLES_RAW);
  return validatedCache;
}

export { getValidatedMockVehicles, MOCK_VEHICLES_RAW as MOCK_VEHICLES };
